# Define job order
stages:
  - lib-build
  
# Define library files
.lib-build-files: &lib-build-files
  only:
    refs:
      - master

# Create library for macos
lib-build-macos:
  <<: *lib-build-files
  stage: lib-build
  tags:
    - osx
  script:
    - git clean -xfd
    - mkdir build
    - mkdir release
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_DRAFTS=ON -DCMAKE_PREFIX_PATH=$HOME/builds/release/ingescape/usr/local/
    - make -C build
    - make -C build DESTDIR=$PWD/release install
    - make -C build DESTDIR=$HOME/builds/release/ingescape/ install
    - cd release/usr/local/
    - tar zcvf ../../../zyre.tgz *
    - cd ../../..
  artifacts:
    paths:
      - zyre.tgz
    name: "lib-build-macos"
    expire_in: 1 day
  dependencies: []



