# Define job order
stages:
  - lib-build
  
# Define library files
.lib-build-files: &lib-build-files
  only:
    refs:
      - master

# Create library for macos
lib-build-macos:
  <<: *lib-build-files
  stage: lib-build
  tags:
    - osx
  script:
    - git clean -xfd
    - mkdir build
    - mkdir release
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_DRAFTS=ON -DCMAKE_PREFIX_PATH=$HOME/builds/release/ingescape/usr/local/
    - make -C build
    - make -C build DESTDIR=$PWD/release install
    - make -C build DESTDIR=$HOME/builds/release/ingescape/ install
    - cd release/usr/local/
    - tar zcvf ../../../zyre.tgz *
    - cd ../../..
  artifacts:
    paths:
      - zyre.tgz
    name: "lib-build-macos"
    expire_in: 1 day
  dependencies: []
  
# Create library for windows
# Library will be build for 4 targets : Debug x86, Debug x64, Release x86, Release x64
lib-build-windows:
  <<: *lib-build-files
  stage: lib-build
  tags:
    - windows
  script:
    - IF "%VS_VERSION_YEAR%"=="" (ECHO ">> VS_VERSION_YEAR must be defined on the Runner side <<" && EXIT /B 1)
    - IF "%VS_VERSION_NUM%"=="" (ECHO ">> VS_VERSION_NUM must be defined on the Runner side <<" && EXIT /B 1)
    - set INITIAL_PATH=%PATH%;%DEPLOYMENT_WINDOWS_NET_SHARE%\Builds\include
    - net use %DEPLOYMENT_WINDOWS_NET_SHARE% /user:%DEPLOYMENT_WINDOWS_USER% %DEPLOYMENT_WINDOWS_PASSWORD%
    - mkdir build && cd build
    - set PATH=%INITIAL_PATH%;%DEPLOYMENT_WINDOWS_NET_SHARE%\Builds\Debug\x86
    - cmake -S .. -B DebugX86 -G"Visual Studio %VS_VERSION_NUM% %VS_VERSION_YEAR%" -DENABLE_DRAFTS=ON -DZYRE_BUILD_STATIC=OFF
    - cmake --build DebugX86 --target ALL_BUILD --config Debug
    - set PATH=%INITIAL_PATH%;%DEPLOYMENT_WINDOWS_NET_SHARE%\Builds\Release\x86
    - cmake -S .. -B ReleaseX86 -G"Visual Studio %VS_VERSION_NUM% %VS_VERSION_YEAR%" -DENABLE_DRAFTS=ON -DZYRE_BUILD_STATIC=OFF
    - cmake --build ReleaseX86 --target ALL_BUILD --config Release
    - set PATH=%INITIAL_PATH%;%DEPLOYMENT_WINDOWS_NET_SHARE%\Builds\Debug\x64
    - cmake -S .. -B DebugX64 -G"Visual Studio %VS_VERSION_NUM% %VS_VERSION_YEAR% Win64" -DENABLE_DRAFTS=ON -DZYRE_BUILD_STATIC=OFF
    - cmake --build DebugX64 --target ALL_BUILD --config Debug
    - set PATH=%INITIAL_PATH%;%DEPLOYMENT_WINDOWS_NET_SHARE%\Builds\Release\x64
    - cmake -S .. -B ReleaseX64 -G"Visual Studio %VS_VERSION_NUM% %VS_VERSION_YEAR% Win64" -DENABLE_DRAFTS=ON -DZYRE_BUILD_STATIC=OFF
    - cmake --build ReleaseX64 --target ALL_BUILD --config Release
    - copy /y ..\include\*.h "%DEPLOYMENT_WINDOWS_NET_SHARE%\Builds\include\" > nul
    - copy /y "DebugX86\Debug\zyre.*" "%DEPLOYMENT_WINDOWS_NET_SHARE%\Builds\Debug\x86\"
    - copy /y "DebugX86\Debug\libzyre.*" "%DEPLOYMENT_WINDOWS_NET_SHARE%\Builds\Debug\x86\"
    - copy /y "ReleaseX86\Release\zyre.*" "%DEPLOYMENT_WINDOWS_NET_SHARE%\Builds\Release\x86\"
    - copy /y "ReleaseX86\Release\libzyre.*" "%DEPLOYMENT_WINDOWS_NET_SHARE%\Builds\Release\x86\"
    - copy /y "DebugX64\Debug\zyre.*" "%DEPLOYMENT_WINDOWS_NET_SHARE%\Builds\Debug\x64\"
    - copy /y "DebugX64\Debug\libzyre.*" "%DEPLOYMENT_WINDOWS_NET_SHARE%\Builds\Debug\x64\"
    - copy /y "ReleaseX64\Release\zyre.*" "%DEPLOYMENT_WINDOWS_NET_SHARE%\Builds\Release\x64\"
    - copy /y "ReleaseX64\Release\libzyre.*" "%DEPLOYMENT_WINDOWS_NET_SHARE%\Builds\Release\x64\"



